version: "3"

services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tr00t
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
